### ISSUE TITLE
We need a logo.

### ISSUE THREAD

**Issue by spoonben** [BuckCoJs/logo#1]
So here is the deal, we need a logo. I have some ideas, but I'd like some input or submissions. 

![buckscojs3](https://cloud.githubusercontent.com/assets/4006413/10792625/d429f558-7d63-11e5-849a-b482231cc448.png)
![buckscojs4](https://cloud.githubusercontent.com/assets/4006413/10792626/d42aba10-7d63-11e5-9a9e-8bb9c88dccf4.png)
![buckscojshorns](https://cloud.githubusercontent.com/assets/4006413/10792627/d433739e-7d63-11e5-83ea-503a2359cfa3.png)
![buckscojsmap](https://cloud.githubusercontent.com/assets/4006413/10792699/2a0b43dc-7d64-11e5-8f35-aada2b557b2a.png)
![buckscojsmap2](https://cloud.githubusercontent.com/assets/4006413/10792698/2a0b2bae-7d64-11e5-83b8-06e19283313d.png)
![buckscojsmap3](https://cloud.githubusercontent.com/assets/4006413/10792700/2a0c8d00-7d64-11e5-950d-78e468f803e1.png)

**Comment by spoonben** [comment]
![buckscojsmapontop](https://cloud.githubusercontent.com/assets/4006413/10801073/e486d89e-7d8b-11e5-88c2-017a4b52b108.png)
![buckscojsmaptop2](https://cloud.githubusercontent.com/assets/4006413/10801074/e4898f76-7d8b-11e5-8b04-619b320080d2.png)

**Comment by spoonben** [comment]
I like these too

![buckscojshead](https://cloud.githubusercontent.com/assets/4006413/10801357/66fce04c-7d8d-11e5-9646-232d096324bd.png)
![buckscojsbody](https://cloud.githubusercontent.com/assets/4006413/10801371/7a05e5c6-7d8d-11e5-87f3-2fe6ebf53c32.png)

**Comment by evandipietro** [comment]
I'd like to see what that last one would look like with the buck further to the right.
Also, the JS with antlers might be better if the antlers were more like the ones on the bucks from the last two.

**Comment by spoonben** [comment]
@evandipietro Eh?

![buckscojsant1](https://cloud.githubusercontent.com/assets/4006413/10819932/4733bc92-7e21-11e5-8b8b-7b5fd4a2d0f7.png)
![buckscojsant2](https://cloud.githubusercontent.com/assets/4006413/10819930/4730917a-7e21-11e5-85b4-4a8818332c4e.png)
![buckscojsant4](https://cloud.githubusercontent.com/assets/4006413/10819931/4731cfa4-7e21-11e5-9c3d-da46184f52e1.png)

**Comment by spoonben** [comment]
@evandipietro Forgot one:

![buckscojsant3](https://cloud.githubusercontent.com/assets/4006413/10819998/92730546-7e21-11e5-9864-633885fd8d13.png)

**Comment by spoonben** [comment]
Oh right, and here is the body moved over a bit:

![buckscojsbodyright](https://cloud.githubusercontent.com/assets/4006413/10820037/b2886fce-7e21-11e5-8755-bc673da8ff4f.png)

**Comment by evandipietro** [comment]
Liking the 2nd to last one

**Comment by spoonben** [comment]
@evandipietro Tweaked it just a tad:

![buckscojstweek](https://cloud.githubusercontent.com/assets/4006413/10820174/4a4b9228-7e22-11e5-9345-374a37072f2b.png)

**Comment by shorttompkins** [comment]
I formatted my computer last night so I dont have graphics capabilities yet, but totally changing the direction a bit for ideas.  What about a play on this?
![screen shot 2015-10-29 at 9 49 09 am](https://cloud.githubusercontent.com/assets/3021049/10820192/626c7f2a-7e22-11e5-8a48-34af626f8c76.png)

**Comment by spoonben** [comment]
Eh, I never liked that html5 logo.

**Comment by spoonben** [comment]
I'll stop tweaking this one if we don't like it, but here is another... 

![buckscojs](https://cloud.githubusercontent.com/assets/4006413/10820226/867f340c-7e22-11e5-9f16-b563a5b5e1d5.png)

**Comment by evandipietro** [comment]
I don't like it when the antlers start clipping or get close to clipping.

**Comment by shorttompkins** [comment]
![1436439824nodejs-logo](https://cloud.githubusercontent.com/assets/3021049/10820275/bb61bcda-7e22-11e5-81a4-c02a5cdadcea.png)

Theres this one too, for some ideas.  Im just kind of really played out/sick of the overly  yellow square.

**Comment by shorttompkins** [comment]
I dont want to be the hater/buzzkill - but the antlers and tech just really really clash with me.  like I "get it" but not a fan.

**Comment by spoonben** [comment]
Haha see I _love_ the yellow square.

**Comment by spoonben** [comment]
Well, we really have like... two options? The county shape - which everyone didn't like. Or something to play on the word "buck".

**Comment by evandipietro** [comment]
The county shape seemed like the only other viable option so far, but it is quite boring.

**Comment by evandipietro** [comment]
The yellow square has really pleasing ascetics, I'm open to other ideas though.
The yellow square also represents community since it is not a corporate logo.

**Comment by shorttompkins** [comment]
well in theory we have unlimited options.  Theres no rule that says the logo actually has to have something to do with a deer or county demarcation :P

**Comment by spoonben** [comment]
+1 @evandipietro

**Comment by evandipietro** [comment]
@shorttompkins We do have unlimited options in theory, but in practice I believe we're best served by something loosely associated with known branding.

**Comment by shorttompkins** [comment]
@evandipietro :hankey:

**Comment by spoonben** [comment]
I totally agree with @evandipietro

**Comment by shorttompkins** [comment]
@spoonben + @evandipietro = :fire: :hankey: :skull:

**Comment by spoonben** [comment]
Okay so now that we know @shorttompkins' vote is out :smile_cat: I think the general consensus was this one so far, right?

![](https://cloud.githubusercontent.com/assets/4006413/10820037/b2886fce-7e21-11e5-8755-bc673da8ff4f.png)

**Comment by shorttompkins** [comment]
i do like that one over the `JS` with antlers

**Comment by spoonben** [comment]
Just messing around, too subtle? 

![buckscojsant5](https://cloud.githubusercontent.com/assets/4006413/10821200/8994ad52-7e27-11e5-853e-ddf5917ec902.png)

**Comment by spoonben** [comment]
Bump

**Comment by spoonben** [comment]
I'm closing this. See readme for our logo.
